# config/validation/appointmentLine.yaml
rules:
  appointment_id:
    type: "string"
    required: true
    nullable: false
    error_message: "Appointment ID is required"
  
  service_id:
    type: "string"
    required: true
    nullable: false
    error_message: "Service ID is required"