# Validation rules for Patient entity
rules:
  email:
    type: "string"
    format: "email"
    required: false
    nullable: true
    error_message: "Invalid email format"
  
  mobile_phone:
    type: "string"
    format: "phone"
    pattern: "^\\+?[0-9]{10,15}$"
    required: true
    nullable: false
    error_message: "Phone number is required and must be valid"
  
  first_name:
    type: "string"
    min_length: 1
    max_length: 100
    required: true
    nullable: false
    error_message: "First name is required"
  
  last_name:
    type: "string"
    min_length: 1
    max_length: 100
    required: true
    nullable: false
    error_message: "Last name is required"
  
  date_of_birth:
    type: "datetime"
    required: false
    nullable: true
    error_message: "Invalid date format"