# config/validation/provider.yaml
rules:
  name:
    type: "string"
    required: true
    nullable: false
    min_length: 1
    error_message: "Provider name is required"
  
  source_provider_id:
    type: "string"
    required: true
    nullable: false
    error_message: "Source provider ID is required"
  
  clinic_id:
    type: "string"
    required: true
    nullable: false
    error_message: "Clinic ID is required"