# config/validation/service.yaml
rules:
  name:
    type: "string"
    required: true
    nullable: false
    min_length: 1
    error_message: "Service name is required"
  
  source_service_id:
    type: "string"
    required: true
    nullable: false
    error_message: "Source service ID is required"
  
  base_price:
    type: "number"
    min_value: 0
    required: true
    nullable: false
    error_message: "Base price must be a non-negative number"